export const mockNews = [
  {
    uuid: "1",
    title: "Breaking News: AI Takes Over the World",
    description:
      "In a stunning development, AI is now controlling everything...",
    url: "https://example.com/news1",
    image_url: "https://via.placeholder.com/300x150",
    source: "Example News",
    published_at: "2025-09-02T12:00:00Z",
  },
  {
    uuid: "2",
    title: "Economy Update: Markets Hit All-Time High",
    description: "Stock markets are soaring after positive economic reports...",
    url: "https://example.com/news2",
    image_url: "https://via.placeholder.com/300x150",
    source: "Example Finance",
    published_at: "2025-09-02T10:00:00Z",
  },
  {
    uuid: "3",
    title: "Sports: Local Team Wins Championship",
    description: "Fans celebrate as the local team clinches the title...",
    url: "https://example.com/news3",
    image_url: "https://via.placeholder.com/300x150",
    source: "Example Sports",
    published_at: "2025-09-01T18:00:00Z",
  },
  {
    uuid: "4",
    title: "React 19 Released",
    description: "React 19 comes with new hooks and features to improve DX.",
    image_url: "https://via.placeholder.com/300x200",
    source: "Tech News",
    published_at: "2025-09-03",
  },
  {
    uuid: "5",
    title: "NASA Discovers Water on Mars",
    description: "New rover images confirm traces of water under Martian soil.",
    image_url: "https://via.placeholder.com/300x200",
    source: "Space Daily",
    published_at: "2025-09-01",
  },
];
